name    'velaluqa-etherpad'
version '0.0.1'
source  'https://github.com/leoc/puppet-etherpad'
author  'Arthur Leonard Andersen'
license 'GPLv3'
summary 'Puppet Etherpad Module'
description 'Module to install Etherpad using puppet'
project_page 'https://github.com/leoc/puppet-etherpad/'
dependency 'willdurand/nodejs', '>= 1.1.3'
