name    'velaluqa-etherpad'
version '1.0.0'
source  'https://github.com/leoc/puppet-etherpad'
author  'velaluqa'
license 'GPLv3'
summary 'Etherpad Module'
description 'Etherpad lite module for Debian'
project_page 'http://github.com/velaluqa/puppet-etherpad'
dependency 'willdurand/nodejs', '>= 1.1.3'
